config/routes.rb
Blogt::Application.routes.draw do
  devise_for :users
  resources :posts

  get 'contact' => 'contact#new', :as => 'contact'
  post 'contact' => 'contact#create'
  get '/testimonials' => 'testimonials#index', :as => 'testimonials'

  get '/terms_of_use' => 'terms#index', as: 'terms_of_use'
  get '/privacy_policy' => 'privacy#index', as: 'privacy'
  get '/contact_us' => 'contact_us#index', as: "contact_us"
  get '/faqs' => 'faqs#index', as: 'faqs'
  get '/updates' => 'updates#index', as: 'updates'

  get '/firm' => 'firm#index', as: 'firm'
  get '/services' => 'services#index', as: 'services'
  get '/home' => 'home#index', as: 'home'
  root "home#index"

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body, :nickname

  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  validates :nickname, absence: true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/messages.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

  private

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  def index
  end
end

app/controllers/firm_controller.rb
class FirmController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = Message.new
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :current_user_present, only: [:new, :edit, :destroy, :update, :create]

  def current_user_present
    unless user_signed_in?
      redirect_to root_url
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :post_date, :post_text)
    end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact/new.html.erb
<div class="span12">
<div class="row">
  <div class="span6 contact column">
    <div id="contactA" class="contentcolumn columnfont">
  <h3>Contact Us</h3>
  <div class="contactdisplay">
   <p>1107 South Mannheim Road, Suite 310<br />Westchester, IL 60154<br />(local) (630) 655-1040<br /><h2>(Toll Free) <a class="hidden-desktop hidden-tablet visible-phone" href="tel:8778811040">877-881-1040</a></h2><h2 class="visible-desktop visible-tablet hidden-phone">877-881-1040</h2><br />(fax) (630) 655-1120<br />
    <br>
    <div class="span3">
    <iframe width="325" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=1107+South+Mannheim+Road,+Suite+310+Westchester,+IL+60154&amp;aq=&amp;sll=41.833733,-87.731964&amp;sspn=0.581186,0.899506&amp;ie=UTF8&amp;hq=&amp;hnear=1107+S+Mannheim+Rd+%23310,+Westchester,+Illinois+60154&amp;t=m&amp;z=14&amp;ll=41.864568,-87.881764&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=1107+South+Mannheim+Road,+Suite+310+Westchester,+IL+60154&amp;aq=&amp;sll=41.833733,-87.731964&amp;sspn=0.581186,0.899506&amp;ie=UTF8&amp;hq=&amp;hnear=1107+S+Mannheim+Rd+%23310,+Westchester,+Illinois+60154&amp;t=m&amp;z=14&amp;ll=41.864568,-87.881764" style="color:#0000FF;text-align:left">View Larger Map</a></small>
  </div>
</div>
</div>
</div>
<div class="span6 contact column">
  <div id="contactB" class="contentcolumn">
  <h3>Email Us</h3>
  <div class="emailform">
<%= form_for @message, :url => contact_path do |form| %>
  <div style="display: none;">
    <%= form.label :nickname %><br/>
    <%= form.text_field :nickname %>
  </div>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </div>
    <div>
      <%= form.label :subject %><br>
      <%= form.text_field :subject %>
    </div>

    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </div>

  <div>
    <%= form.submit "Send" %>
  </div>
<% end %>

</div>
</div>
</div>
</div>
</div>

app/views/faqs/index.html.erb
  <div class="faq span12">
    <div id="faqA" class="contentcolumn columnfont">
  <h1>FAQs</h1>
      <h4>I received a letter from the IRS, what should I do?</h4>
<p>Contact us right away for a consultation. Requests from the IRS and other taxing authorities have timelines for replies and penalties could be assessed for late responses.</p>
<h4>How much will the consultation cost?</h4>
<p>The initial consultation is free. After that, our fees vary according to the services we provide. We have various payment plans available to help our clients solve their problems. Your particular situation will be discussed during your free consultation.</p>
<h4>How can the IRS collect money from me or my company?</h4>
<p>The IRS can file a federal tax lien against all your assets; levy your bank accounts and/or wages; seize your home, investments, retirement, cars, business, or anything of value and dispose of them through an auction sale.</p>
<h4>What do I do if I don't have any money to pay the IRS?</h4>
<p>One of the Tax Relief, Inc. specialists will advise you during your free consultation of the best path to take to solve your tax problem.</p>
<h4>What is an Offer in Compromise?</h4>
<p>An Offer in Compromise (OIC) is an agreement whereby the IRS agrees to accept less than what they are owed from a taxpayer.</p>
<h4>Am I qualified for an Offer in Compromise?</h4>
<p>Contact us to see if you qualify. There are specific IRS standards regarding eligibility including ratios of Income vs Expenses and assets that may be available for liquidation. Working with a tax professional can make a big difference when preparing an Offer in Compromise. According to a recent report from the National Taxpayer Advocate, almost one quarter of all OICs submitted were rejected because they were filled out incorrectly, and of the applications that were initially accepted for processing, almost half were later rejected.</p>
<h4>How long will the recovery process take?</h4>
<p>Some steps, such as stopping levies and seizures may happen relatively quickly. However, the entire process of an Offer in Compromise can take several months to over a year or more.</p>
<h4>Where are you located and will I need to come to your office?</h4>
<p>Tax Relief, Inc. serves clients from across the nation. Most of our work can be handled via telephone, Internet, and mail. If you are coming to our office for any reason, please click here for directions.</p>
<h2 class="faqbottom">Contact us to schedule your free consultation today</h2>
<div class="faqbottomnumber"><a class="hidden-desktop hidden-tablet visible-phone" href="tel:8778811040"><h2>877-881-1040</a></h2><h2 class="visible-desktop visible-tablet hidden-phone">877-881-1040</h2></div>
 </div>
</div>

app/views/firm/index.html.erb
       <div id="firmcolumn">
<div class="row">
  <div id="firmA" class= "contentcolumn">
    <h1>Who is Tax Relief Inc.?</h1>
     <ul>
     <li>Over 55 years of combined experience among our partners</li>
     <li>Tax Relief, Inc. has been working with clients since 1987</li>
     <li>Tax Relief, Inc. partners work with you right from the free consultation</li>
     </ul>
     <div class="firmimage span12"><%= image_tag asset_url("Tim.jpg"), class: "imagetim", alt: "Mr. Foley" %></div><p>Mr. Foley is the Managing Director of Tax Relief, Inc. Mr. Foley is an Enrolled Agent and Certified Management Accountant. He served as Chairman of the Executive Committee of a $1.2 billion distribution company. He was instrumental in turning around the financially troubled Medaille College (Buffalo, New York)
and later named as Medaille's Chairman of the Board. Mr. Foley has concentrated his efforts on working with taxpayers that have collection problems with the IRS. As an Enrolled Agent, Mr. Foley is authorized to represent taxpayers nationwide before the Internal Revenue Service.</p><br />
<br />
<br />
<div id="firmB" class="firmimage span12"><%= image_tag asset_url("Joe.jpg"), class: "imagetim", alt: "Mr. Shadle" %></div>
<p>Mr. Shadle is President of Tax Relief, Inc. Mr.
Shadle is an Enrolled Agent and Certified Tax Resolution Specialist. He worked for eight years in the Financial Services industry in New York,
New Jersey and Florida. His work experience includes service for the Small Business Administration providing disaster relief loans to individuals and corporations subsequent to the attacks on World Trade
Center. He is a graduate of Rochester Institute of Technology with a
major in International Finance. His focus and current experience is in Tax and Management Consulting.</p><br />
<br />
<br />
<h3 class="bottomfirmcolumn">The problem will not go away on its own</h3>

<h3 class="bottomfirmcolumn">Contact us today for a free, no-obligation consultation</h3>
<br />
<h3 class="bottomfirmnumber"><a class="hidden-desktop hidden-tablet visible-phone" href="tel:8778811040">877-881-1040</a></h3><h3 class="visible-desktop visible-tablet hidden-phone bottomfirmnumber">877-881-1040</h3></div>
</div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
<div class="row">
  <div id="maintext" class="span8">
    <div class="columnfont contentcolumn column1">
        <iframe width='100%' height='315' src='http://video.bbb.org/embed/index.php?&noAd=1&noPreRoll=1&noPostRoll=1bureauId=1030&vid=2458' frameborder='0' allowfullscreen></iframe>
       <h3>Tax Relief</h3>
         <ul>
           <li>Expert IRS navigation</li>
           <li>Timely resolution</li>
           <li><u>A+ Rating From The Better Business Bureau</u></li>
           <li>In-depth knowledge of the Taxpayer Bill of Rights</li>
           <li>Innovative solutions to complex tax problems</li>
             <ul>
                <li>Liens and levies</li>
                <li>Garnishments</li>
                <li>Unfiled returns</li>
                <li>Outstanding payroll taxes</li>
                </ul>
          </ul>
        </div>
    </div>
    <div id="frontemail" class="span4">
      <div id="frontemailtop" class="contentcolumn columnfont column1">
        <h3>Send Us A Message:</h3>
        <%= form_for @message, :url => contact_path do |form| %>
          <div style="display: none;">
            <%= form.label :nickname %><br/>
            <%= form.text_field :nickname %>
           </div>
           <div>
            <%= form.label :name %><br>
            <%= form.text_field :name %>
           </div>
           <div>
             <%= form.label :email %><br>
             <%= form.text_field :email %>
           </div>
           <div>
             <%= form.label :subject %><br>
             <%= form.text_field :subject %>
           </div>
           <div>
             <%= form.label :body %><br>
             <%= form.text_area :body %>
           </div>
           <div>
            <%= form.submit "Send" %>
           </div>
        <% end %>
    </div>
  </div>
</div>
  <div class="row">
  <div id="leftcolumn" class="span4">
    <div id="mission" class="columnfont contentcolumn column">
      <h3>Our Mission</h3>
        <p>To utilize the experience and knowledge of our Tax Relief, Inc. accredited professionals to successfully resolve the unique tax matters of each client</p>
        <p>Personal complimentary Initial consultation to find the best remedy</p>
        <p>Alleviate both financial and emotional burden resulting from tax problems by reaching a successful resolution through strategic negotiations with the IRS</p>
     <br />
     <br />
      <div style="width: 200px;" align="center"> <a target="_blank"
 id="bbblink" class="ruhzbum"
 href="http://www.bbb.org/chicago/business-reviews/taxes-consultants-and-representatives/tax-relief-in-westchester-il-88000094#bbblogo"
 title="Tax Relief, Inc., Taxes - Consultants &amp; Representatives, Westchester, IL"
 style="margin: 0px; padding: 0px; display: block; position: relative; overflow: hidden; width: 150px; height: 68px;"><img
 style="border: medium none ; padding: 0px;" id="bbblinkimg"
 src="http://seal-chicago.bbb.org/logo/ruhzbum/tax-relief-88000094.png"
 alt="Tax Relief, Inc., Taxes - Consultants &amp; Representatives, Westchester, IL"
 height="68" width="300"></a>
      <script type="text/javascript">var bbbprotocol = ( ("https:" == document.location.protocol) ? "https://" : "http://" ); document.write(unescape("%3Cscript src='" + bbbprotocol + 'seal-chicago.bbb.org' + unescape('%2Flogo%2Ftax-relief-88000094.js') + "' type='text/javascript'%3E%3C/script%3E"));</script></div>
<br />
<br />
<div>
<%= image_tag asset_url("NAEA-Logo.jpg"), :alt => "National Association of Expert Advisors", :class => "frontnaea hidden-phone" %>
</div>
<div>
<%= image_tag asset_url("ASTPS_Icon1small.jpg"), :alt => "American Society for Tax Problem Solvers", :class => "frontnaea hidden-phone" %></div>
<div>
<%= image_tag asset_url("nationalasstax.jpg"), :class => "frontnaea", :alt => "National Association of Tax Resolution Companies hidden-phone" %>
</div>
  </div>
</div>

  <div id="centercolumn" class="span4">
    <div id="taxlien" class="contentcolumn columnfont column">
     <h3>Tax Lien</h3>
   <h4>Impact of a lien</h4>
   <ul>
    <li>A lien attaches to all of your current assets (property, securities, vehicles) and future assets acquired during the duration of the lien</li>
     <li>Limits your availability to get credit</li>
     <li>Attaches to all business property and all rights to business property, including accounts receivable</li>
     <li>Filing for bankruptcy does not always wipe out your tax debt and liens</li>
   </ul>
    <h4>How to get rid of a lien</h4>
   <ul>
     <li>The IRS releases your lien within thirty days of receiving full payment</li>
     <li>A Discharge of Property allows your property to be sold free of the lien via submission of Publication 783</li>
     <li>Subordination does not remove the lien, but allows other creditors to move ahead of the IRS which may make it easier to get a loan or mortgage</li>
     <li>Withdrawal removes the public notice and assures that the IRS is not competing with other creditors for your property</li>
   </ul>
   <br>
   </div>
 </div>
  <div id="rightcolumn" class="span4">
    <div id="taxappeal" class="contentcolumn columnfont column">
<h3>Tax Appeal</h3>
  <ul>
  <li>Large volumes of appeals</li>
  <li>The appeal process is very lengthy and takes weeks to complete</li>
  <li>Appeals are difficult to navigate-it's easy to miss a required step resulting in a denial</li>
  <li>Tax Relief will familiarize you with and protect your Taxpayer Bill of Rights throughout the process</li>
  <li>Tax Relief will openly communicate and guide you through the appeal to ensure all necessary and appropriate steps are taken</li>
  <li>Tax Relief will guide you through the application process and ensure all the correct documentation is complete</li>
</ul>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tax Relief Inc.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
<script src="dist/html5shiv.js"></script>
<![endif]-->

</head>
<body>
   <div id="masthead">
    <div class="container">
      <div class="row">
      <div class="logo span6">
        <div class="contentcolumnslogan">
      <%= image_tag asset_url("highresolutionlogo.png"), alt: "Tax Relief", size: "296x83" %>
    </div>
  </div>
    <div class="slogan span6">
      <div class="contentcolumnslogan">
      <h4><strong>Your Tax Relief Partner<br> Call </h4><a class="hidden-desktop hidden-tablet visible-phone" href="tel:8778811040"><h4>877-881-1040</a></h4><h4 class="visible-desktop visible-tablet hidden-phone">877-881-1040</h4><br>
<a href="mailto:joe@taxreliefinc.com" class="hidden-desktop">Email Us</a>

      <div class="social_media">
<a href="https://twitter.com/share" class="twitter-share-button" data-via="TaxReliefIncIl">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script><!-- Place this tag where you want the +1 button to render. -->
<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="300"></div>
<!-- Place this tag after the last +1 button tag. -->
</div>
</div>

    </div>
    </div>
  </div>
  </div>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>

        </a>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Firm", firm_path %></li>
            <li><%= link_to "Updates", posts_path %></li>
            <li><%= link_to "Testimonials", testimonials_path %></li>
            <li><%= link_to "FAQs", faqs_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>


<div class="backgroundcolor">
    <div class="container">
<%= yield %>
</div>
</div>
<div class="footerbottom">
  <div class ="container">
  <h3>&#169 2014 Tax Relief Inc.<br> Call <a class="hidden-desktop hidden-tablet visible-phone" href="tel:8778811040"><h3>877-881-1040</a></h3><h3 class="visible-desktop visible-tablet hidden-phone">877-881-1040</h3><br>
  <%= link_to "Sign In", new_user_session_path  %> <%= link_to "Privacy Policy", privacy_path %> <%= link_to "Terms of Use", terms_of_use_path %>
</div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br>
    <%= f.date_select :post_date %>
  </div>
  <div class="field">
    <%= f.label :post_text %><br>
    <%= f.text_area :post_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div id="updatescolumn">
    <div class="contentcolumn">
      <% if current_user.present? %>
        <%= link_to "Add Post", new_post_path %>
        <% end %>
    <h1>Tax Updates</h1>
    <% @posts.each do |post| %>
    <ul style="list-style-type:none">
      <li>
        <div>
        <h3><%= post.title %><br>
          <%= post.post_date.strftime("%B %d, %Y") %></h3>
        <p><%= post.post_text %></p>
        <hr>
        </div>
      </li>
    </ul>
    <% end %>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Post date:</strong>
  <%= @post.post_date %>
</p>

<p>
  <strong>Post text:</strong>
  <%= @post.post_text %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/privacy/index.html.erb
<div class="container">
  <h1>Privacy Policy</h1>
  <p style="font-size:16px"><strong>What information do we collect?</strong></p>
<p style="font-size:12px">We collect information from you when you fill out a form.
When ordering or registering on our site, as appropriate, you may be asked to enter your: name, e-mail address or phone number. You may, however, visit our site anonymously.</p>
<p style="font-size:16px"><strong>What do we use your information for?</strong></p>
<p style="font-size:12px">Any of the information we collect from you may be used in one of the following ways:
<ul>
<li style="font-size:12px">To process transactions
-Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested.</li>
<li style="font-size:12px">To send periodic emails
-The email address you provide may be used to send you information, respond to inquiries, and/or other requests or questions.</li>
</ul>
<p style="font-size:16px"><strong>Do we use cookies?</p>
<p style="font-size:12px">Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information
We use cookies to keep track of advertisements and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future. We may contract with third-party service providers to assist us in better understanding our site visitors. These service providers are not permitted to use the information collected on our behalf except to help us conduct and improve our business.</p>
<p style="font-size:16px"><strong>Do we disclose any information to outside parties?</p>
<p style="font-size:12px">We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>
<p style="font-size:16px"><strong>California Online Privacy Protection Act Compliance</p>
<p style="font-size:12px">Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.</p>
<p style="font-size:16px"><strong>Childrens Online Privacy Protection Act Compliance</p>
<p style="font-size:12px">We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.</p>
<p style="font-size:16px">Your Consent</p>
<p style="font-size:12px">By using our site, you consent to our privacy policy.</p>
<p style="font-size:16px">Changes to our Privacy Policy</p>
<p style="font-size:12px">If we decide to change our privacy policy, we will post those changes on this page.</p>
<p style="font-size:16px">Contacting Us</p>
<p style="font-size:12px">If there are any questions regarding this privacy policy you may contact us using the information below.</p>
<p>www.taxreliefinc.com<br />
1107 South Mannheim Rd, Suite 310<br />
Westchester, IL 60154<br />
Joe@taxreliefinc.com<br />
877-881-1040a
</div>